name: Lives from YouTube

on:
  workflow_dispatch:

jobs:
  build-playlist:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Instalar dependências
        run: |
          sudo curl -L https://github.com/yt-dlp/yt-dlp/releases/latest/download/yt-dlp -o /usr/local/bin/yt-dlp
          sudo chmod a+rx /usr/local/bin/yt-dlp
          sudo apt-get update && sudo apt-get install -y jq

      - name: Criar arquivo de cookies a partir do Secret
        run: echo "${{ secrets.YOUTUBE_COOKIES }}" > cookies.txt

      - name: Gerar playlist.m3u
        id: generate_playlist
        run: |
          echo "#EXTM3U" > playlist.m3u
          echo "## Playlist atualizada em: $(date)" >> playlist.m3u

          # ESTRUTURA DE DADOS CORRIGIDA: Usando 'live_url' em vez de 'handle'
          CHANNELS_JSON='
          [
            {"category": "Cams", "name": "CGTN Europe", "logo": "https://yt3.googleusercontent.com/ytc/AIdro_m72n4fRBXMnz-Q8YYhrzAUhNf_O1bAK1NbikOPVNT_RY4Z=s250-c-k-c0x00ffffff-no-rj", "live_url": "https://youtube.com/@CGTNEurope/live"},
            {"category": "Cams", "name": "DD Cyprus 1 Click", "logo": "https://yt3.googleusercontent.com/IYcuUOia0WFk0QSsz6z8TJ4rCZD6g0iIOTj6J5ptDdRkqVjnbxpeaPNljEVZb1_fhUSU5OeaWQ=s250-c-k-c0x00ffffff-no-rj", "live_url": "https://youtube.com/@DDCyprus1Click/live"},
            {"category": "Cams", "name": "Intel Cams Live", "logo": "https://yt3.googleusercontent.com/9qCAVGoCSMpCoqo5mEsgJRV2kfIZXil-4GXCetocjMZV2dOKYdtB38qklAwGF6XQFe_ftBOf2g=s250-c-k-c0x00ffffff-no-rj", "live_url": "https://youtube.com/@intelcamslive/live"},
            {"category": "Cams", "name": "Source Global", "logo": "https://yt3.googleusercontent.com/v4qJg_xkfgUHKXm5mN0_y6GylnprLvX0EaH8sy7SBUScOlF9FlC92tE7u1wMGx6eBnM8E98iaeo=s250-c-k-c0x00ffffff-no-rj", "live_url": "https://youtube.com/@SourceGlobal/live"},
            {"category": "Music", "name": "80s Neon Wave", "logo": "https://yt3.googleusercontent.com/sypT9xRGY5TwhNEk-w1Yd5AY5k3d3a5OwjYusLd1On_9horzQXfwTR1dOlMKKXGLlN0XrfQ61fc=s250-c-k-c0x00ffffff-no-rj", "live_url": "https://youtube.com/@80sNeonWave/live"},
            {"category": "Music", "name": "Dj Scenester", "logo": "https://yt3.googleusercontent.com/ytc/AIdro_kbXAllJOqn9_wNNSyjm9-nLWmQCLwu55NHXsJNUmej4g=s250-c-k-c0x00ffffff-no-rj", "live_url": "https://youtube.com/@DjScenester/live"},
            {"category": "Music", "name": "Lofi Girl", "logo": "https://yt3.googleusercontent.com/G9eB57HDQaxqp-qX8jYd_6uAYJYc9f47ndkF3X1_5hIgzwSn7zqewJroMOQJerxJFDSTfhyBYg=s250-c-k-c0x00ffffff-no-rj", "live_url": "https://www.youtube.com/LofiGirl/live"},
            {"category": "Music", "name": "NightRide FM", "logo": "https://yt3.googleusercontent.com/U_bXLU8CTmYo3LHxZP00zxYnL5wE6socvOK4B5oOymD4r82a3Dyr09n21N0ZmCWBilmygCUpubU=s250-c-k-c0x00ffffff-no-rj", "live_url": "https://www.youtube.com/NightrideFM/live"},
            {"category": "Music", "name": "StarBurst Music", "logo": "https://yt3.googleusercontent.com/W0zacIAIJDl7QPV9BgLt_OZaarkoPfRTd7vt4e9yuJHEKW_sdIfJjigoGbFi7U0cOLzVZ2RAZg=s250-c-k-c0x00ffffff-no-rj", "live_url": "https://youtube.com/@starburstmusic/live"},
            {"category": "Music", "name": "ThePrimeThanatos", "logo": "https://yt3.googleusercontent.com/ytc/AIdro_kxZe_UovXSbfRON-ll6D15gscBQtuDF1bmrfLUW3a635g=s250-c-k-c0x00ffffff-no-rj", "live_url": "https://youtube.com/@ThePrimeThanatos/live"},
            {"category": "Music", "name": "Vibe Retro", "logo": "https://yt3.googleusercontent.com/BFLqeqrKZ4wVVAmbE0hDNs_kX4pQF5cbb7WGSVcp-ZaB08kLQWJAXB7TcGuR8d9lNq1wWvLE8A=s250-c-k-c0x00ffffff-no-rj", "live_url": "https://youtube.com/viberetro/live"},
            {"category": "News", "name": "ABC News", "logo": "https://yt3.googleusercontent.com/GJ8V0NX6NddGh9bf4zED4tsjPjjBK2hdp5FWHMy09pV7sdSkkE3yEhCRSch4waEb9ZavyUrWfw=s250-c-k-c0x00ffffff-no-rj", "live_url": "https://www.youtube.com/ABCNews/live"},
            {"category": "News", "name": "Al Jazeera Arabic", "logo": "https://yt3.googleusercontent.com/oN_i26ADOuQ4PdypHo8yjVXh6QSXZ1kMeYzaRH3hNOlQE1uEUUQ-gkCh0o1rUQ2PM7Qx6QvY2g=s250-c-k-c0x00ffffff-no-rj", "live_url": "https://www.youtube.com/aljazeera/live"},
            {"category": "News", "name": "Al Jazeera English", "logo": "https://yt3.googleusercontent.com/IQJ3YwNpaJRPpOM1Gab8xBZiDhsgq2gtM3KZQKk8JCZjhxOPxuuzyUVCTWpyp9eAEyS-QQsdRA=s250-c-k-c0x00ffffff-no-rj", "live_url": "https://www.youtube.com/aljazeeraenglish/live"},
            {"category": "News", "name": "Associated Press", "logo": "https://yt3.googleusercontent.com/I2UXf4n7ukd9hl7UQDsPKN0QXQ9X_NoujZfOY_qPhbBwyJv-K3-rFsrWIDGc3CFylr2cL2c7=s250-c-k-c0x00ffffff-no-rj", "live_url": "https://youtube.com/@AssociatedPress/live"},
            {"category": "News", "name": "CNN Brasil", "logo": "https://yt3.googleusercontent.com/ytc/AIdro_lmJE_9aX-lvy2eliMO5ejbko3mQVM6Ecf79AR8pQFMcV8=s250-c-k-c0x00ffffff-no-rj", "live_url": "https://www.youtube.com/CNNbrasil/live"},
            {"category": "News", "name": "CRUX", "logo": "https://yt3.googleusercontent.com/ytc/AIdro_lvuTdsdT3Di7NszY9LTOcCmUVVG8nRnPAZpe_a7Y7MR6k=s250-c-k-c0x00ffffff-no-rj", "live_url": "https://www.youtube.com/CRUXnews/live"},
            {"category": "News", "name": "FRANCE 24 English", "logo": "https://yt3.googleusercontent.com/ytc/AIdro_n_QTJ5-GLGnftQFkb7Kp36W2eBH3H-7ZqTQxzFkkqGrIE=s250-c-k-c0x00ffffff-no-rj", "live_url": "https://www.youtube.com/France24_en/live"},
            {"category": "News", "name": "LiveNOW from FOX", "logo": "https://yt3.googleusercontent.com/AqzY5ePezRAQ2136-TbM_88d43JfIovkzztge92WKQ4K_ISfJMFA9yuX0Nw87DLWms4W9r2c3Q=s250-c-k-c0x00ffffff-no-rj", "live_url": "https://www.youtube.com/livenowfox/live"},
            {"category": "News", "name": "NBC News", "logo": "https://yt3.googleusercontent.com/PJj5jtuEOi5UmkFy4IBonj5WcabNcnJAIJe-jZMd1ArwIuVyQxFH_2zryBHwvfv6mJujwRpWDCM=s250-c-k-c0x00ffffff-no-rj", "live_url": "https://www.youtube.com/NBCNews/live"},
            {"category": "News", "name": "Reuters", "logo": "https://yt3.googleusercontent.com/bCcVVrrV0EhGFJKsSvmeZHA9Y-YzSL9Keqrrr0HWYUPQy3-mVUVNHMbjwt7IoVkpsHt4E6BZ3pM=s250-c-k-c0x00ffffff-no-rj", "live_url": "https://www.youtube.com/Reuters/live"},
            {"category": "News", "name": "Sky News", "logo": "https://yt3.googleusercontent.com/dGnkztdrLtXRlzkdqReeL-NES2761xxmNVcJhGKqFpR0vQBoP9XaxnXF95FDpwrjyFr2iJvV8Es=s250-c-k-c0x00ffffff-no-rj", "live_url": "https://www.youtube.com/SkyNews/live"},
            {"category": "News", "name": "WION", "logo": "https://yt3.googleusercontent.com/evxeFzRem76hjPRh_S_B5MvjNhl4yKjSrIzmvwFx3nyEWHBOPHA4jTum6Yys3HRR0IvYmWud=s250-c-k-c0x00ffffff-no-rj", "live_url": "https://www.youtube.com/WION/live"},
            {"category": "Rap", "name": "Rap Mafia", "logo": "https://yt3.googleusercontent.com/r-yXkd01G9Hdmp-TIserE6mvxDOkBnjFLwwRXh2KV2lRpNBKtS3TZp4OC1JnFGbJKHyLZ5ko=s250-c-k-c0x00ffffff-no-rj", "live_url": "https://www.youtube.com/RapMafia/live"},
            {"category": "Tornadoes", "name": "Max Velocity", "logo": "https://yt3.googleusercontent.com/QVJYHZBym6DV7mG79BE0xTz15M__f0XsqlB5bYxK451imSpTZpHSozUt2ButAZXEhCn0ZZtl=s250-c-k-c0x00ffffff-no-rj", "live_url": "https://www.youtube.com/MaxVelocityWX/live"},
            {"category": "Tornadoes", "name": "Reed Timmer", "logo": "https://yt3.googleusercontent.com/BYAjOyMjBFkO6U8ztN7EVSxr1ej7US65pgEN6NfxqN3rDX0atiCAFYwm9unxVBZK5NsNySc77ao=s250-c-k-c0x00ffffff-no-rj", "live_url": "https://www.youtube.com/ReedTimmerWx/live"},
            {"category": "Tornadoes", "name": "Ryan Hall Yall", "logo": "https://yt3.googleusercontent.com/ytc/AIdro_m6cYR5IDSUUx72T9eKzzh7IOQ-E5-e9mLjFaMPmZlejss=s250-c-k-c0x00ffffff-no-rj", "live_url": "https://www.youtube.com/RyanHallYall/live"}
          ]
          '

          echo "$CHANNELS_JSON" | jq -c '. | sort_by(.category, .name) | .[]' | while IFS= read -r line; do
            CATEGORY=$(echo "$line" | jq -r '.category')
            NAME=$(echo "$line" | jq -r '.name')
            LOGO=$(echo "$line" | jq -r '.logo')
            # LÓGICA CORRIGIDA: Pega a URL da live diretamente.
            LIVE_URL=$(echo "$line" | jq -r '.live_url')

            echo "Loading..."
            echo "Verificando: $NAME"
            echo "--> URL da Live: $LIVE_URL"

            # Comando usa a URL direta da live, que é muito mais confiável.
            M3U8_URL=$( (timeout 30 yt-dlp --cookies cookies.txt -f b --get-url "$LIVE_URL" | grep 'm3u8' | head -n 1) || true )
            
            if [ -n "$M3U8_URL" ]; then
              echo "  --> SUCESSO: Canal online. URL M3U8 encontrada."
              echo "" >> playlist.m3u
              echo "#EXTINF:-1 tvg-logo=\"$LOGO\" group-title=\"$CATEGORY\",$NAME" >> playlist.m3u
              echo "$M3U8_URL" >> playlist.m3u
            else
              echo "  --> FALHA: Live não encontrada nesta URL específica. Pode estar offline."
            fi
          done
          
          echo "..."
          echo "Verificação de todos os canais concluída."

      - name: Fazer commit das alterações
        run: |
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor_id }}+${{ github.actor }}@users.noreply.github.com"
          git add playlist.m3u
          if [ $(wc -l < playlist.m3u) -gt 2 ]; then
            git commit -m "Atualiza a playlist de lives do YouTube"
            git push
            echo "Playlist atualizada com sucesso e enviada para o repositório."
          else
            echo "Nenhuma live foi encontrada. Nenhum commit será feito."
          fi
